### ISSUE TITLE
Java not installed and stucked on finalizing

### ISSUE THREAD

**Issue by KareenaKapoor** [etechd/L3MON#28] opened 2020-01-21 07:44 UTC
java -version
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b01-1-b01)
OpenJDK 64-Bit Server VM (build 25.212-b01, mixed mode)

showing error java not installed error and stuck on finalizing

**Comment by Jack-Rogers** [comment] 2020-01-21 21:15
Duplicate of #19 
Please bear with me, I'm looking into this issue. 
Also please check other open issues and comment on those before creating a duplicate.

**Closed by Jack-Rogers** 2020-01-21 21:15 UTC
