### ISSUE TITLE
Stuck on finalizing

### ISSUE THREAD

**Issue by akib2002** [etechd/L3MON#12] opened 2019-11-25 17:09 UTC
Hello, whenever i try to build with my ubuntu vps, it stuck on finish...

I've installed everything as mentioned in readme

**Comment by akib2002** [comment] 2019-11-25 17:10
Event log says
25/11/2019, 15:30:46 => SUCCESS | Build Succeded!
25/11/2019, 15:30:38 => SUCCESS | Build Succeded!

**Comment by Jack-Rogers** [comment] 2019-12-10 13:45
Duplicate of #1

**Closed by Jack-Rogers** 2019-12-10 13:45 UTC
